export { default as DefaultLayout } from './DefaultLayout.vue'
export { default as AuthLayout } from './AuthLayout.vue'
export { default as DashboardLayout } from './DashboardLayout.vue'
export { default as LegalLayout } from './LegalLayout.vue'
export { default as ErrorLayout } from './ErrorLayout.vue'
